### PR TITLE
bump version to 2.5.25

### PR DESCRIPTION
**Pull request by js8544**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by js8544** [comment]
@conda-forge-admin, please rerender

**Comment by js8544** [comment]
@hmaarrfk It's been a week since the checks passed. Would you mind having a look at this PR? Thanks.

**Comment by hmaarrfk** [comment]
Can you add yourself as a maintainer below and rerended?

**Comment by js8544** [comment]
@conda-forge-admin, please add user @js8544

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
